apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: consumer
  labels:
    app: consumer
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer-app
        image: smyhus/receiver
