apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-service
spec:
  type: ClusterIP
  selector:
   app: rabbitmq
  ports:
  - port: 5672
    name: amqp
    targetPort: 5672

  - port: 15672
    name: html
    targetPort: 15672
